baseurl = "https://djzager.github.io"
languageCode = "en-us"
title = "David Zager's Blog"
author = "@djzager"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/djzager\">David Zager</a> 2017"
disqusShortname = ""
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true
enableEmoji = true
pygmentsCodeFences = true

[params.rss]
includeContent = true
authorName = "David Zager"
authorEmail = "david.j.zager@gmail.com"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "djzager"
github = "djzager"
email = "david.j.zager@gmail.com"
linkedin = "djzager"
facebook = ""
instagram = ""
codepen = ""
rs = "index.xml"

[params.social.config]
platforms = ["twitter", "github", "linkedin", "email", "rs"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
